# Generated by Django 4.1 on 2022-11-15 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Offer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("for_purchase", models.BooleanField(default=False)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
                ),
                ("description", models.CharField(blank=True, max_length=150)),
                ("status", models.CharField(default="processing", max_length=100)),
                ("created_on", models.DateField(auto_now_add=True)),
                ("last_modified", models.DateField(auto_now=True)),
            ],
            options={
                "db_table": "offers",
            },
        ),
    ]
